version: '3'

services:
  node_app:
    container_name: my_node_container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    command: npm start
