version: "3.8"
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    postgres:
      image: "postgres:latest"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      networks:
        - database_network
      redis:
        image: "redis:latest"
        ports:
          - "6379:6379"
        networks:
          - database_network
    networks:
      database_network: null
